### ISSUE TITLE
CSU San Marcos Data Migration

### ISSUE THREAD

**Issue by aaron-collier** [csuscholarworks/migration_status#4]
- [x] Export DSpace Communities
- [x] Transfer data to AWS Data Loader
- [ ] Import Data into Hyrax
- [ ] Produce Handle Report
- [ ] Review Metadata
